- name: "Setup Docker nodes"
  hosts: "docker"
  become: true
  tasks:
    - name: Update and upgrade OS
      apt:
        update_cache: true
        upgrade: true
    - name: Install docker
      apt:
        name: docker.io
        state: present
        update_cache: true
    - name: Grant docker sudo permissions
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Indentify yourself
      command: whoami
      changed_when: false
# This is the equivelant of running the following commands on the server
# sudo apt update
# sudo apt upgrade
# sudo apt update
# sudo apt install docker.io
# sudo usermod -aG docker $USER
# sudo whoami
